name: "test-release-action"

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
  push:
    branches:
      - master

jobs:
  create-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine next version
        id: getVersion
        uses: Luke-Rogerson/pr-bump-version@v1.1.0
      - name: Create Github Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: version
          tag: ${{ steps.getVersion.outputs.version }}"
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
